//
// Created by Jordan on 10/10/2023.
//

#ifndef BOMBERVALI_GAMECHAR_H
#define BOMBERVALI_GAMECHAR_H

enum class GameChar {
    PLAYER = 2,
    BREAKABLE_WALL = 178,
    WALL = 219,
    BOMB = 162,
    ENEMY = 184,
    BOMB_CONSUMABLE = 11,
    POWER_UP_DISTANCE_BOOST = 224,
    POWER_UP_IGNORE_WALLS = 157,
};

#endif //BOMBERVALI_GAMECHAR_H
